[parity]
chain = "demo-spec.json"
base_path = "/tmp/parity1"
[network]
port = 30303
[rpc]
port = 8545
apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces", "parity_accounts"]
[websockets]
port = 8546
[ipc]
disable = true